//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalArtefactManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int LikeId { get; set; }
        public Nullable<bool> IsLiked { get; set; }
        public Nullable<int> ArticleId { get; set; }
        public string UserName { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
